[context.production.environment]
  CMS_BRANCH = "master"

[context.staging.environment]
  CMS_BRANCH = "staging"

[build]
  publish = "public/"
  command = "sed -i \"s/branch: master/branch: ${CMS_BRANCH}/g\" static/admin/config.yml && npm run build"

[build.environment]
  NODE_VERSION = "18.16.0"
  NPM_VERSION = "9.5.1"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/handbook/*"
  to = "/:splat"
  status = 200