backend:
  name: git-gateway
  repo: middlebury/college-handbook
  branch: master
  accept_roles: ["admin", "editor"]

media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow

collections:
  - name: "middlebury-wide"
    label: "I. Middlebury Wide Policies"
    folder: "content/i-policies-for-all"
    path: "{{slug}}/"
    create: true
    fields:
      - {
          label: "Title",
          name: "title",
          default: "document name",
          widget: "string",
          required: false,
        }
      - {
          label: "Text",
          name: "body",
          widget: "markdown",
          buttons: ["heading-one", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "bold", "italic", "link", "bulleted-list", "numbered-list"],
          editor_components: ["table"],
          required: false,
        }
  - name: "undergraduate-college"
    label: "II. Policies for the Undergraduate College"
    folder: "content/ii-ug-college-policies"
    path: "{{slug}}/{{slug}}/{{slug}}/"
    create: true
    fields:
      - {
          label: "Title",
          name: "title",
          default: "document name",
          widget: "string",
          required: false,
        }
      - {
          label: "Text",
          name: "body",
          widget: "markdown",
          buttons: ["heading-one", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "bold", "italic", "link", "bulleted-list", "numbered-list"],
          editor_components: ["table"],
          required: false,
        }
  - name: "language-schools"
    label: "III. Policies for the Language Schools"
    folder: "content/iii-policies-for-the-language-schools"
    path: "{{slug}}/"
    create: true
    fields:
      - {
          label: "Title",
          name: "title",
          default: "document name",
          widget: "string",
          required: false,
        }
      - {
          label: "Text",
          name: "body",
          widget: "markdown",
          editor_components: [],
          required: false,
        }
  - name: "miis-policies"
    label: "IV. Policies for the Institute of International Studies"
    folder: "content/iv-policies-for-the-institute"
    path: "{{slug}}/{{slug}}/"
    create: true
    fields:
      - {
          label: "Title",
          name: "title",
          default: "document name",
          widget: "string",
          required: false,
        }
      - {
          label: "Text",
          name: "body",
          widget: "markdown",
          buttons: ["heading-one", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "bold", "italic", "link", "bulleted-list", "numbered-list"],
          editor_components: ["table"],
          required: false,
        }
  - name: "previous-handbooks"
    label: "Previous Handbooks"
    folder: "content/v-handbook-archive"
    path: "{{slug}}/"
    create: true
    fields:
      - {
          label: "Title",
          name: "title",
          default: "document name",
          widget: "string",
          required: false,
        }
      - {
          label: "Text",
          name: "body",
          widget: "markdown",
          buttons: ["heading-one", "heading-two", "heading-three", "heading-four", "heading-five", "heading-six", "bold", "italic", "link", "bulleted-list", "numbered-list"],
          editor_components: ["table"],
          required: false,
        }
